#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PatternPreset {
    Pct5,
    Pct10,
    Pct20,
    Pct25,
    Pct30,
    Pct40,
    Pct50,
    Pct60,
    Pct70,
    Pct75,
    Pct80,
    Pct90,
    Horz,
    Vert,
    LtHorz,
    LtVert,
    DkHorz,
    DkVert,
    NarHorz,
    NarVert,
    DashHorz,
    DashVert,
    Cross,
    DnDiag,
    UpDiag,
    LtDnDiag,
    LtUpDiag,
    DkDnDiag,
    DkUpDiag,
    WdDnDiag,
    WdUpDiag,
    DashDnDiag,
    DashUpDiag,
    DiagCross,
    SmCheck,
    LgCheck,
    SmGrid,
    LgGrid,
    DotGrid,
    SmConfetti,
    LgConfetti,
    HorzBrick,
    DiagBrick,
    SolidDmnd,
    OpenDmnd,
    DotDmnd,
    Plaid,
    Sphere,
    Weave,
    Divot,
    Shingle,
    Wave,
    Trellis,
    ZigZag,
    Unknown(String),
}

impl PatternPreset {
    pub fn from_ooxml(value: &str) -> Self {
        match value {
            "pct5" => Self::Pct5,
            "pct10" => Self::Pct10,
            "pct20" => Self::Pct20,
            "pct25" => Self::Pct25,
            "pct30" => Self::Pct30,
            "pct40" => Self::Pct40,
            "pct50" => Self::Pct50,
            "pct60" => Self::Pct60,
            "pct70" => Self::Pct70,
            "pct75" => Self::Pct75,
            "pct80" => Self::Pct80,
            "pct90" => Self::Pct90,
            "horz" => Self::Horz,
            "vert" => Self::Vert,
            "ltHorz" => Self::LtHorz,
            "ltVert" => Self::LtVert,
            "dkHorz" => Self::DkHorz,
            "dkVert" => Self::DkVert,
            "narHorz" => Self::NarHorz,
            "narVert" => Self::NarVert,
            "dashHorz" => Self::DashHorz,
            "dashVert" => Self::DashVert,
            "cross" => Self::Cross,
            "dnDiag" => Self::DnDiag,
            "upDiag" => Self::UpDiag,
            "ltDnDiag" => Self::LtDnDiag,
            "ltUpDiag" => Self::LtUpDiag,
            "dkDnDiag" => Self::DkDnDiag,
            "dkUpDiag" => Self::DkUpDiag,
            "wdDnDiag" => Self::WdDnDiag,
            "wdUpDiag" => Self::WdUpDiag,
            "dashDnDiag" => Self::DashDnDiag,
            "dashUpDiag" => Self::DashUpDiag,
            "diagCross" => Self::DiagCross,
            "smCheck" => Self::SmCheck,
            "lgCheck" => Self::LgCheck,
            "smGrid" => Self::SmGrid,
            "lgGrid" => Self::LgGrid,
            "dotGrid" => Self::DotGrid,
            "smConfetti" => Self::SmConfetti,
            "lgConfetti" => Self::LgConfetti,
            "horzBrick" => Self::HorzBrick,
            "diagBrick" => Self::DiagBrick,
            "solidDmnd" => Self::SolidDmnd,
            "openDmnd" => Self::OpenDmnd,
            "dotDmnd" => Self::DotDmnd,
            "plaid" => Self::Plaid,
            "sphere" => Self::Sphere,
            "weave" => Self::Weave,
            "divot" => Self::Divot,
            "shingle" => Self::Shingle,
            "wave" => Self::Wave,
            "trellis" => Self::Trellis,
            "zigZag" => Self::ZigZag,
            unknown => Self::Unknown(unknown.to_owned()),
        }
    }

    pub fn as_ooxml(&self) -> &str {
        match self {
            Self::Pct5 => "pct5",
            Self::Pct10 => "pct10",
            Self::Pct20 => "pct20",
            Self::Pct25 => "pct25",
            Self::Pct30 => "pct30",
            Self::Pct40 => "pct40",
            Self::Pct50 => "pct50",
            Self::Pct60 => "pct60",
            Self::Pct70 => "pct70",
            Self::Pct75 => "pct75",
            Self::Pct80 => "pct80",
            Self::Pct90 => "pct90",
            Self::Horz => "horz",
            Self::Vert => "vert",
            Self::LtHorz => "ltHorz",
            Self::LtVert => "ltVert",
            Self::DkHorz => "dkHorz",
            Self::DkVert => "dkVert",
            Self::NarHorz => "narHorz",
            Self::NarVert => "narVert",
            Self::DashHorz => "dashHorz",
            Self::DashVert => "dashVert",
            Self::Cross => "cross",
            Self::DnDiag => "dnDiag",
            Self::UpDiag => "upDiag",
            Self::LtDnDiag => "ltDnDiag",
            Self::LtUpDiag => "ltUpDiag",
            Self::DkDnDiag => "dkDnDiag",
            Self::DkUpDiag => "dkUpDiag",
            Self::WdDnDiag => "wdDnDiag",
            Self::WdUpDiag => "wdUpDiag",
            Self::DashDnDiag => "dashDnDiag",
            Self::DashUpDiag => "dashUpDiag",
            Self::DiagCross => "diagCross",
            Self::SmCheck => "smCheck",
            Self::LgCheck => "lgCheck",
            Self::SmGrid => "smGrid",
            Self::LgGrid => "lgGrid",
            Self::DotGrid => "dotGrid",
            Self::SmConfetti => "smConfetti",
            Self::LgConfetti => "lgConfetti",
            Self::HorzBrick => "horzBrick",
            Self::DiagBrick => "diagBrick",
            Self::SolidDmnd => "solidDmnd",
            Self::OpenDmnd => "openDmnd",
            Self::DotDmnd => "dotDmnd",
            Self::Plaid => "plaid",
            Self::Sphere => "sphere",
            Self::Weave => "weave",
            Self::Divot => "divot",
            Self::Shingle => "shingle",
            Self::Wave => "wave",
            Self::Trellis => "trellis",
            Self::ZigZag => "zigZag",
            Self::Unknown(value) => value,
        }
    }
}
